FROM elixir:latest

RUN apt-get update && \
    apt-get install -y inotify-tools && \
    apt-get install -y nodejs && \
    curl -L https://npmjs.org/install.sh | sh && \
    mix local.hex --force && \
    mix archive.install hex phx_new 1.6.9 --force && \
    mix local.rebar --force

ENV APP_HOME /app
WORKDIR $APP_HOME

CMD ["mix", "phx.server"]

# For debugging when server fails to start
# CMD ["tail", "-f", "/dev/null"]